### ISSUE TITLE
Patching order for newComms patch compatibility

### ISSUE THREAD

**Issue by Gordon-Dry** [DRVeyl/RealAntennas#1]
To have your patches be compatible with my newComms patches which also have to obey some MM logic I suggest that you change at least the following:

GameData/RealAntennas/RealAntennas.cfg
line 168
AFTER[RealismOverhaul] -> AFTER[zzzRealismOverhaul]

**Comment by Gordon-Dry** [comment]
Oh, there is a typo in your config, too...
For sanity, even better would be:
```
@PART[*]:HAS[@MODULE[ModuleConfigurableAntenna],!MODULE[ModuleRealAntenna]]:AFTER[zzzRealismOverhaul]
{
	@MODULE[ModuleConfigurableAntenna]
	{
		@name = ModuleRealAntenna
	}
}
```

**Comment by Gordon-Dry** [comment]
See my branch's commits to better understand why:
https://github.com/Gordon-Dry/RealismOverhaul/commits/TEST

**Comment by DRVeyl** [comment]
Accepted and merged.
