### ISSUE TITLE
RO/RP-1 S-band  Avalible at T-0

### ISSUE THREAD

**Issue by SerinaTsukaya** [DRVeyl/RealAntennas#12]
Hi
I don't know if this is a configuration made by real antenna or if it's made by Ro/RP, but I thought I'd try to post here first. Basically new carrer mode save, I have S-band unlocked from the very start, which is apparently a very modern way of data transmission, I also have VHF and UHF.

**Comment by DRVeyl** [comment]
S-band unlocks at TL0 in RA through Beta 5.  The -current- master branch has the config to unlock S-band at TL3, but these changes have not been packaged into the 0.6 release yet.
