### ISSUE TITLE
Tracking Center Upgrade?

### ISSUE THREAD

**Issue by hxl11211** [DRVeyl/RealAntennas#15]
I am currently on a play-through with RP-1 and Kerbalism. If I understand correctly, with RealAntennas  the communication range is solely determined by the antenna(s) installed on spacecrafts? I didn't find anything in the wiki explaining how would tracking center upgrades affect the communication performance.

BTW, this mod is _simply_ awesome. Thanks!

**Comment by DRVeyl** [comment]
The ground station sites also have their own sets of antennas.  These upgrade with the TS level, treating that the same as the TechLevel of an antenna part.  Many of the properties of the ground station upgrades are configured in the .cfg files, particularly in RealAntennasCommNetParams (around line 334) or RealismOverhaul.cfg (around line 160).  Typically this is in dish size increases, lower noise = better sensitivity, or access to new bands/encoders.

Some of the properties of antenna parts are in the TechLevel definitions in the RealAntennasCommNetParams or RealismOverhaul files.  Most of those aren't applicable to the ground stations, but access to the encoder and band properties are.

I'm terrible at maintaining my own wiki, but I'll nudge some of the other players to update it and address this.  (That's the great thing about a wiki!)

**Comment by DRVeyl** [comment]
With <https://github.com/DRVeyl/RealAntennas/releases/tag/v1.2>, in the Editor (VAB/SPH) you can now choose the tech level of the tracking station for the planner.  This will let you see the effects of an upgrade.
