### ISSUE TITLE
Active/Inactive Power Levels per Tech Level

### ISSUE THREAD

**Issue by ChubbyTurtle101** [DRVeyl/RealAntennas#18]
The active power levels decrease as tech increases but the idle numbers don't make sense.  Also the numbers are the same for all probe cores and antennas.  Transmit power (dBm) was set to 30.  Why does Idle power mac at 25.7 watts at tech level 4?  Why are the power ratings the same for all antennas and probe cores?
Level    Active Power (watts)    Idle Power (watts)
0          18.2                               2.0
1          13.0                               0.3
2          10.0                               8.0
3          7.67                             19.5
4          6.00                             25.7
5          4.50                             23.0
6          4.00                             21.4
7          3.33                             18.3
8          2.69                             18.3
9          2.27                             11.7
10        2.27                             11.7

Testing with Kerbalism, Unkerballed Start, and RealAntennas and support mods in 1.8.1

**Comment by ChubbyTurtle101** [comment]
How may tech levels 10 or 11?  It appears that tech level 10 is a duplication of tech level 9.

Should the "Tech Level" be "Radio Tech" since it controls the efficiency and radio band?   Maybe having the radio type instead of the numbers 0-10?  What exactly is the Idle power?  

Also in build Beta 8.1 there is no VHF/UHF.  There is only L, S, X, K bands.

**Comment by DRVeyl** [comment]
I'll start with the caveat that the idle power values do not make sense from a non-RO perspective, and I will adopt a more obvious progression of idle power across tech levels in the default/stock settings.

In the context of RO, the data is sourced from exemplar real-world probes during each era.  However, they had differing capabilities (ie receiver complexity), and that is not obvious, presented to the player, or really even modeled in RA.  This will likely remain as "working as designed" in RO even if it's quite opaque.

There is no specific definition of TL10 in the configs, so it is defaulting to the next highest TL.  The tech levels are defined by .cfg, so the maximum is configurable.

I assume you built from the repo to get your 1.8.1 dll, as I have no public releases supporting that.  (I have done only a couple of test builds for a few individuals.  Or are you running the 1.7.3 build in a 1.8.1 environment?)

I don't understand the question about the power rating.  Unless that is a holdover PAW field from stock-like behavior that is not being hidden.

The idle power essentially corresponds to power consumed by the receiver electronics.

UHF and VHF, and some of the encoders, were moved from the stock configuration into the RO-specific one.  L/S/X/K are the stock bands.

**Comment by ChubbyTurtle101** [comment]
I am using the 1.7.3 build in my 1.8.1 test game.  I did not see the dev 1.8.1 branch until after I started testing.  Is the 1.8.1 branch at a place where it can be compiled?  Are there any further items needed to complete the 1.8.1 build?  I guessing that you are using Visual Studio to compile the C# code.

To me it was not clear what Active/Idle meant.  I am assuming that there is standby power consumption (i.e when not transmitting) but the antenna is activated, the power usage by the radio/receiver equipment when transmitting,  I am guessing Active power value is the amount of power just for generating the radio wave?  What is the conversion from watt to EC/sec?

It just looks weird that at tech level 4 that the idle is 25.7 watts but transmitting is only 6 watts while tech level 1 idle is 0.3 watts and active is 13  watts.  So is the 6 watts on top of the 25.7 watts?  

Since the idle power corresponds to the power consumed by the receiver, this is why I suggest to name each the tech levels or call it radio tech level as it refers to the electrons and not the antenna,  This makes since why those ratings are the same for all antennas.

I just came back to KSP and Kerbalism is not longer providing support for RemoteTech and it appears the RO is going the same route.  I appreciate your work on this mod.  It fills a nice void.

**Comment by DRVeyl** [comment]
The 1.8 branch looks up-to-date and compile-able.  Current active development is for 1.7 right now, and aperiodically I merge those changes to the 1.8 branch.  When Kopernicus releases for 1.8 (enabling RO to do so), RealAntennas will follow shortly.  Correct, I am using Visual Studio.  You would need to fix the post-build events (convenience, not required) and the Unity & KSP references (required) for your environment.

Idle represents standby draw and applies whenever an antenna is deployed.  Active represents _additional_ power draw for transmitting.  You pay the total cost (and the latest Kerbalism release will display both values separately).

1 kilowatt = 1 ec/sec.

Problem is the tech level also applies to the antenna properties.  Mass & cost factors and reflector efficiency are wrapped in there.

Appreciate the feedback!

**Comment by DRVeyl** [comment]
Mass, Power and Cost scaling in stock setting have been made monotonic as of https://github.com/DRVeyl/RealAntennas/commit/2827c870277d2a417baaa1a6228f3086f82d772b
