### ISSUE TITLE
No commnet at launchpad

### ISSUE THREAD

**Issue by theburning** [DRVeyl/RealAntennas#22]
I started a science mode game. I have extra ground stations turned off and I'm using the Simplex Tech Tree. I put a probe on the launchpad and I have no connection to commnet. Is this expected?

ETA: This also happens with extra ground stations enabled as well as in career mode. Adding an antenna to the probe (only one available at the start) only adds a second antenna that also can't connect to commnet. Are unmanned-first games impossible with this mod?

ETA: Further research reveals there are NO ground stations, even at KSC. I really don't know what to make of this.

**Comment by DRVeyl** [comment]
My first guess is that CommNet is not turned on in the difficulty settings.  Do you have the icons visible in the upper left to indicate?  (There should be a warning screen-message if this is the case.)

"Extra ground stations" setting has no effect.  I am not sure about using the Simplex Tech Tree, if the various TL unlocks will be available there without configuration, but that is a later problem.

If you attach your KSP.log, that would be helpful.

**Comment by theburning** [comment]
CommNet was definitely turned on. As for not having unlocks, that shouldn't matter in science mode, should it? I'll try it without the tech tree, just to see the results.
The only thing I could figure is that there's no antenna target, but I have no idea how that's done. Especially with a probe.

[KSP.log](https://github.com/DRVeyl/RealAntennas/files/4270933/KSP.log)

**Comment by theburning** [comment]
I just tested without Simplex Tech Tree, and there's no CommNet connection for the crewed ship I put on the launchpad either.

**Comment by DRVeyl** [comment]
You appear to have two copies of ModuleManager active.  You should delete 4.1.0 and keep 4.1.3.

You also have Kopernicus, but without a planet pack.  Your issue is https://github.com/DRVeyl/RealAntennas/issues/20.  See the conversation there.  I don't have a specific fix for this yet.

**Comment by theburning** [comment]
Kopernicus is supposed to be uninstalled, since it isn't working with the current KSP. Thanks for catching it.

**Comment by DRVeyl** [comment]
Believe this is fixed in https://github.com/DRVeyl/RealAntennas/commit/52b509ee6e47b2c65f7ffb9f0e958ffe6b94e193 and available in the latest 1.8 pre-release updated today.
