### ISSUE TITLE
Losing communication and insufficient avionics after ~30Mm away from Earth?

### ISSUE THREAD

**Issue by boeing186** [DRVeyl/RealAntennas#23]
I've tried multiple variations, but no matter what I do whenever I leave about 30Mm from Earth in RSS I get a notification saying that I have "insufficient avionics (0.000 T/5.000T)" (or something like that) and I can no longer toggle SAS. RCS works, but only in vertical translation (H-key). Furthermore, Mechjeb's SmartASS doesn't move the craft, I still have green communication with Earth's groundstations, my batteries onboard still have charge, I have multiple antennas, and my power is at 60. However, regardless of everything, whenever I pass about 30Mm it shuts down my avionics and SAS. When I do get back within about 30Mm though everything works ok again.

This issue persists even when I have a procedural avionics package and a regular avionics package well over my craft's mass. To test, I put a 200T avionics package on my ~4T craft and it still shut down outside that range.

**Comment by DRVeyl** [comment]
Issue is with your avionics, not your communications.  You have "Near Earth" avionics and need to select "Deep Space."  This is an RP-1 control locker feature, and is not related to your comms mod.
