### ISSUE TITLE
Antennas draining too much power.

### ISSUE THREAD

**Issue by SuddenButterfly** [DRVeyl/RealAntennas#24]
I don't if this is really an issue but i couldn't find any answer and i don't know where else to write this. Problem is i'm using real antennas and realism overhaul, i'm also new and just trying to build a sounding rocket, but my electric power goes to zero after approximately 20 seconds later. When i disable the antennas there is no problem. I tried using lower transmit powers, switched frequencies but nothing helped. I don't even now if this is what supposed to be and i'm doing it completely wrong. I really be thankful to any help.

**Comment by DRVeyl** [comment]
Are you also using Kerbalism?

Likely, CommNet is disabled in the difficulty settings.  Enable it.

There _should_ be a warning/notification message on screen that it is disabled, but in some situations it does not display.  Next release will address that [and also possibly make the power consumption not insane when CommNet is disabled.]

**Comment by SuddenButterfly** [comment]
I' also using Kerbalism but as you adressed problem was disabled CommNet and i couldn't see any warning. Enabling CommNet solved my problem. Thank you very much for your help.
