### ISSUE TITLE
Feature request: Target antenna to active vessel

### ISSUE THREAD

**Issue by t-liu93** [DRVeyl/RealAntennas#28]
Can I request a feature to target antenna to active vessel? Just like the similar feature existing in RemoteTech. If I understand correctly, currently I can only target an antenna to a body or a specific vessel.

**Comment by DRVeyl** [comment]
Was a design choice not to do this, but can revisit.

One significant issue: What is the target of your antenna when there IS no active vessel, ie you are in the spacecenter or tracking station scenes?  This is not relevant to a stock perspective, but is very important for things like Kerbalism that entail background processing.

What is the use case, that isn't met by pointing at a planet, especially a smaller dish with a lower gain (= higher beamwidth?)  And isn't met by the vessel communicating directly with a ground station, but requires a relay?

**Comment by t-liu93** [comment]
Is that possible say, if there is no active vessel then the antenna will be set to point to the earth. I'm not sure whether this will affect Kerbalism, but I think in the use case of this config, the satellite is usually equipped with more than 1 antenna. 
 
And for that use case, I have a relay network with only limited satellites, in a highly elliptical orbit, say Molniya orbit. And in order to get good communication speed, I am using a dish with small beamwidth but relatively high gain.
And if I am launching a LEO mission, for instance to a 200km polar orbit, then in most of the time, the satellite will have no connection to the ground station. In this case, I can only communicate through a relay, in this case is that satellite in Molniya orbit, which is far away from LEO. Therefore a regular UHF antenna with low gain will now work and I need a dish with high gain. 
Usually I equip my relay satellite with 2 dishes, one point to the earth and the other point to a vessel. If I am only pointing to the earth then due to the low beamwidth, the mission vessel will not be in the beam most of the time, and if I have another dish pointing to the mission vessel and let the mission vessel also point to the relay, then it can get signal.

As a workaround I can also just switch to the relay and then manually point one of its dishes to my mission vessel, but I think it's really good to have at least a choice to let it automatically point to the active vessel.

**Comment by DRVeyl** [comment]
IMO things get very problematic when the system starts repointing your antennas, especially when it points them one way in the space center scene (where you cannot observe what is happening) versus in flight.  Discrepancies between the map view in flight, and the map view in the tracking station, are just asking for confusion and mistakes.

Also, as your example satellite is in its HEO or Molniya orbit, most of the LEO environment is within the view of its antenna looking at Earth.  That's an advantage of the orbit.  You should have no problem just closing a link for control by adjusting the power on the relay (with its directional antenna) and on the LEO vessel (with an omni antenna).  You can use the planner for just such a case, comparing the link between two antennas.  You can place both on the craft in the VAB, or you can plan with a vessel that is currently live in the game, and see how much power you need.

**Comment by t-liu93** [comment]
I understand your concern about the problems which may be caused by repointing the antennas. 
Thanks for your reply.
