### ISSUE TITLE
Wider range for planning distance slider in PAW

### ISSUE THREAD

**Issue by DarthPointer** [DRVeyl/RealAntennas#30]
@DRVeyl has suggested a metric unit switch (Mm, Gm, Tm and so on).

I'm opening an issue in order not to get the idea forgoten.

**Comment by DRVeyl** [comment]
Added in <https://github.com/DRVeyl/RealAntennas/commit/bb2d550f7b1aaa4bed25026e8f0abce9955704b0> and released with 1.2.1
