### ISSUE TITLE
excuse me,could you make a signal delay in real antenna,like remotetech? 

### ISSUE THREAD

**Issue by CindyRIng** [DRVeyl/RealAntennas#32]
before now,I always play realism overhaul with remotetech,from now,I get this mod and feel exciting,but,i also want to play signal delay that  makes me must use kos to play the game. so could you add a signal delay in this mod.
sorry,my english is not good.please forgive me,if some sentence wrong.

**Comment by DRVeyl** [comment]
No. Signal delay mechanics, in terms of capture and delayed execution of all user input, including that meant for other mods (like MJ, or KoS, or any other autopilot), is far outside the scope of RealAntennas.

**Comment by CindyRIng** [comment]
OK I see,thanks.
