### ISSUE TITLE
When loading vessel in VAB the Antenna Planner settings are lost

### ISSUE THREAD

**Issue by Gordon-Dry** [DRVeyl/RealAntennas#4]
I built a brand new vessel and saved it.
Later I came back to VAB and loaded it.
The setting for "Planning peer" (the chosen celestial body) was gone and the setting for "Planning Altitude" was reset to 1.

**Comment by DRVeyl** [comment]
The planner settings are not intended to be persistent.

**Comment by Gordon-Dry** [comment]
Wow. So "just load the vessel" and then "fiddle the same values again I already fiddled the last time".
Okay, every player will love this. Kinda immersion ...

**Comment by Gordon-Dry** [comment]
When I want to change the "Planning Altitude" I even can only move the slider in steps of 10 ...
