### ISSUE TITLE
New HG-5 High Gain Antenna broken

### ISSUE THREAD

**Issue by Ivoz** [DRVeyl/RealAntennas#43]
In higher patches, I think they added a variant, HighGainAntenna5_v2

**Comment by BScCollateral** [comment]
I believe Ivoz is correct. Adding

@PART[HighGainAntenna5_v2] { @mass = 0.001 }
@PART[HighGainAntenna5_v2]:FOR[RealAntennas]
{
    %MODULE[ModuleRealAntenna] { %antennaDiameter = 0.5 }
}

to Gamedata\Realantennas\RealAntennas.cfg seems to fix the issue.

**Comment by Tahvohck** [comment]
This applies to the HG-20 from RestockPlus as well. (new name `restock-relay-radial-2_v2`)
