### ISSUE TITLE
CommNet failure after some gameplay

### ISSUE THREAD

**Issue by kjpg** [DRVeyl/RealAntennas#45]
Running fresh install of tsp 1.10.11 with up-to-date RSS/RO/RP-1, running on a Mac with 11.4/Big Sur.
getting a consistent failure with (I suspect) RA.  career games comms are fine but after a few contracts, and usually around building downrange vehicle with avionics (probably coincidence), the comm network is never available at the launchpad.  earlier crafts don't work either.  If I start a new game and move the craft files, they work.  So, it's something becoming corrupted during play.  I have attached below log entries for a game with the failure and then a NEW game with working comms and the exact same craft file.

[existing game no comms.pdf](https://github.com/DRVeyl/RealAntennas/files/6462821/existing.game.no.comms.pdf)
[fresh game same craft file.pdf](https://github.com/DRVeyl/RealAntennas/files/6462822/fresh.game.same.craft.file.pdf)

**Comment by DRVeyl** [comment]
Difficult to work with 10 lines of a log file if I wasn't already familiar with the issue.
Since you mentioned RO/RP-1, I'm going to assume you are using KCT's sim feature, and further that you probably recently crashed out of KSP during a KCT Sim.  There's a known issue here where when returning to the game, the network doesn't have any nodes.

While I make a more permanent fix to that issue, there is a workaround:  cause the game to update its persistent.sfs again, and load back in.  Returning to the Main Menu and then reloading the save is probably quickest and has resolved the issues.

**Comment by DRVeyl** [comment]
Fixed with <https://github.com/DRVeyl/RealAntennas/commit/49f3c994774ba5e592f653bf66e3b7c92bc3ba24>

**Comment by kjpg** [comment]
thanks.

**Comment by kjpg** [comment]
thanks. I posted selected code since I don't have the log for the moment that it first happens, so more probably wouldn't have helped. thanks again for the fix.

**Comment by kjpg** [comment]
49f3c99 not working.  RealAntenna GUI options do not appear in right-click info panel for craft.  craft files show error for "missing part module ModuleRealAntenna".  comms not available on launch pad.  
reverting to previous RA fixes issues

[KSP.log](https://github.com/DRVeyl/RealAntennas/files/6504016/KSP.log)

**Comment by DRVeyl** [comment]
Where did you get the build?  That is symptomatic of not having the plugin.  Don't get from the branch, get the release, please.  (The zip in your Gamedata makes me think you tried to pull the branch, since the release is named RealAntennas-v2.0.zip)

**Comment by kjpg** [comment]
I followed the install directions from a rss/rp-1 install video.  This works for the previous RA (other than the bug I was having) and the other mods.  

I downloaded the zip from your RA "code" menu, copied the RealAntennas folder from the unzipped gamedata into my KSP gamedata directory. the Zip file referred to in the log file is something I made to easily switch back and forth between the previous and latest RA builds.

**Comment by DRVeyl** [comment]
I do not keep the plugin (the dll file) in the repo.  Downloading anything from the "code" page is incorrect, and getting RA that way has never worked.  Get the release from the release page: <https://github.com/DRVeyl/RealAntennas/releases>.  This is highlighted on the main wiki page: <https://github.com/DRVeyl/RealAntennas/wiki>

**Comment by kjpg** [comment]
indeed.  the old folder did have the plugin.  thanks!
