### ISSUE TITLE
Transmission rate doesn't update upon antennas deploying/retracting

### ISSUE THREAD

**Issue by tofof** [DRVeyl/RealAntennas#49]
### Observed Behavior
Probe using an RC-O OKTO core and two C2 HG-5's (one L band, one S band).
Current stituation: orbiting Kerbin, antennas deployed, relaying data (Kerbalism) through a probe orbiting Mun of same configuration.
If I **retract the antennas, the transmission carries on at the high rate** as displayed in Kerbalism and the link in the tooltip in the top left of the stock UI continues to show the high data rate.
If I then change views to **unload the probe, the transmission rate then falls dramatically** -- apparently only at this point does RA realize the transmission must use the omni on the probe core. 
Change views back to the probe and extend the antennas - same thing happens. **Continue to get low data rate until I unload the probe again, at which point it updates** to use the deployed HG-5. 
Changing the deployed/undeployed state of the relay probe follows the same pattern - no change to the transmission rate until the changed vessel is unloaded. 
Time warp has no effect.
When RA thinks the HG-5's are in use (either correctly -- antennas are deployed and transmission rate reported in UI matches expectations; or incorrectly -- antennas have been stowed but I haven't yet unloaded the vessel), changing the target of the HG-5's causes an immediate update to transmission speed. In other words, aiming the HG-5 away from suitable relays causes an immediate drop, which is similarly immediately reversible by aiming correctly.
Changing the deployed/retracted state causes an immediate update of the list of antennas inside the RA control console. 
When RA thinks the HG-5s are not in use - particularly, after deploying but before unloading the vessel, targeting the antennas differently has no effect.

### Expected behavior
Deploying an antenna makes it immediately available for use.
Stowing an antenna makes it immediately unavailable for use.

### Versions
KSP 1.11.2 with all DLC
RealAntennas v2.0 (current)
Kerbalism 3.13 (current)

**Comment by DRVeyl** [comment]
Fixed in https://github.com/DRVeyl/RealAntennas/commit/f59101264cd95616fb4c00201e11ab82dc0bf528
