### ISSUE TITLE
Some NFE antennas not receiving RA configs - broken cfg at line 108/115, see comment

### ISSUE THREAD

**Issue by tofof** [DRVeyl/RealAntennas#53]
### Observed Behavior
The NFE_CAE_RTREDEV.cfg file seems to have configs for 100% of the following antennas, however, only about half of them work in-game.

AX-4 Pointable Helical Antenna - OK
AX-5 Aerial Micro-Antenna - OK
AX-30 High Gain Micro-Antenna - OK
D0-2 Spot Antenna - **missing RealAntennas in-game**
DR-1 High Gain Antenna - **missing RealAntennas in-game**
DR-3 Deployable High Gain Antenna - OK
F-DA Direct Antenna Feed - **missing RealAntennas in-game**
F-RA Relay Antenna Feed - **missing RealAntennas in-game**
PH-1 Phased Array Antenna Element - **missing RealAntennas in-game**
PH-2 Phased Array Antenna Element - **missing RealAntennas in-game**
RA-00-2 Micro-Relay Antenna - **missing RealAntennas in-game**
RA-0-8 Relay Antenna - OK
RA-X1 Phased Relay Antenna - OK
RFL-1 Dish Reflector - OK

### Expected behavior
All the antennas listed in RA's compatibility cfg end up with RealAntennas functionality in-game.

### Other information
I spot-checked several of the broken parts to make sure the names used by NFE matched those in the NFE_CAE_RTREDEV.cfg, and both seemed to agree. 

### Versions
KSP 1.11.2 with all DLC
RealAntennas 2.0
NearFutureExploration 1.1.1
(all are the most current on CKAN)

**Comment by tofof** [comment]
Found the problem. [Lines 108 and 115](https://github.com/DRVeyl/RealAntennas/blob/151b7d1e1edc8e8ea2135cc452b012a9bf83d524/GameData/RealAntennas/Parts/NFE_CAE_RTREDEV.cfg#L108-L115) the last character is a `}` when it should be a `]` which breaks everything later than line 108 in the file.

**Comment by DRVeyl** [comment]
Also further lines in -- all the NEEDS[!RealismOverhaul] end with the invalid character.  Bad copy-paste.  Thankyou.  Will fix for 2.1.  (Have a bunch of things in the works, probably won't push a 2.0.1 before then)
