### ISSUE TITLE
typo in NFE_CAE_RTREDEV.cfg

### ISSUE THREAD

**Issue by emiliofloris** [DRVeyl/RealAntennas#54]
I noticed by chance 4 typos of the form

`@PART[RTGigaDish2]:HAS[!MODULE[ModuleRealAntenna]]:FOR[RealAntennas]:NEEDS[!RealismOverhaul}`

Note the winged bracket at the end. The parts affected are C5+ RelayTech One and C3+ Relay Antenna RA-7. I didn't check if this has any influence on the game itself, but the MM doesn't seem to have any complaints...

**Comment by DRVeyl** [comment]
Duplicate of <https://github.com/DRVeyl/RealAntennas/issues/53>.  Fix forthcoming.
