### ISSUE TITLE
"incompatible with this version of ksp"

### ISSUE THREAD

**Issue by kjpg** [DRVeyl/RealAntennas#55]
tried with RA 2.0 and RA 2.1 and says the dll file is incompatible. I am running ksp 1.10.1 on a mac. 

[LOG 09:40:28.318] ******* Log Initiated for Kerbal Space Program - 1.10.1.2939 (OSXPlayer) en-us *******
Kerbal Space Program - 1.10.1.2939 (OSXPlayer) en-us

OS: Mac OS X 10.13.6
CPU: Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz (8)
RAM: 16384
GPU: ATI Radeon HD 4850 OpenGL Engine (512MB)
SM: 45 (OpenGL 3.3 ATI-10.4.14)
RT Formats: ARGB32, Depth, ARGBHalf, Shadowmap, RGB565, ARGB4444, ARGB1555, Default, ARGB2101010, DefaultHDR, ARGB64, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8, BGRA32, RGB111110Float, RG32, RG16, BGRA10101010_XR, BGR101010_XR, R16

"[LOG 09:40:36.587] [ModuleManager] Intercepted a ReflectionTypeLoadException. List of broken DLLs:
RealAntennas 2.1.0.0 GameData/RealAntennas/Plugins/RealAntennas.dll"

**Comment by DRVeyl** [comment]
Did you get KSPBurst, a required dependency of RA v2+?

**Comment by kjpg** [comment]
umm ... No.  There is no mention of that in the readme or within the RA wiki, or on your install directions. Where should I have seen that?  (actual question not a rhetorical quip).

**Comment by kjpg** [comment]
fwiw, the CKAN implementation for Mac has issues so I did this manually.

**Comment by DRVeyl** [comment]
The third sentence in the RA 2.0 release (https://github.com/DRVeyl/RealAntennas/releases), still in bold letters.
"Supports 1.8.1 - 1.11
Major performance overhaul addressing late-game performance, using Unity Jobs + Burst.
Now requires KSPBurst, available on CKAN."

**Comment by kjpg** [comment]
I see.  My apologies. But when I click through on DRVeyl/RealAntennas it takes me to the 2.1 release (which doesn't mention Burst), which I thought was the latest because of something you posted on discord.

Installed Burst and 2.1 and it seems to work.  thanks

**Comment by DRVeyl** [comment]
I'm very, very confused, because I have not published a 2.1 release.  Or a 2.1 pre-release.  As far as I know, the only place to find a build of 2.1 is the RA channel on the RO Discord, where I make some dev previews available for testing.  I assume -that- is what you're using?

**Comment by kjpg** [comment]
I'm confused, too. I was browsing discord recently and saw mention of 2.1, so I assumed that was officially released.  As I said, clicking to your GitHub brings up the 2.1 version, not the latest release.  Perhaps it might make sense for the default starting page to be "latest release"? I assumed that was what I was arriving at; I didn't see nor look for the "latest release" stuff over on the right.  I used the "Download Zip" from the code dropdown menu.  This was how I was shown (a YouTube tutorial) to get some of the mods for RP-1 that weren't available through CKAN. Obviously, not preferred behavior I guess.  I'll get the 2.0

**Comment by DRVeyl** [comment]
Going to the main page: <https://github.com/DRVeyl/RealAntennas> ... this is not a release at all.  This is the master branch.  You're looking in a repository for source code.  I don't think I have control over which page is the default (ie, users automatically redirecting to \releases).  Clicking "Download Zip" got you the RA source code.  Yes, this is a way to get a lot of mods, where you do that, then go find Gamedata\<Mod> and copy those contents.  This won't work with RA (or several other mods).  This is what the Wiki Home page <https://github.com/DRVeyl/RealAntennas/wiki> is trying to tell folks not to do.
