### ISSUE TITLE
Ksp stuck on " Loading part upgrades"

### ISSUE THREAD

**Issue by priyanshurohilla** [DRVeyl/RealAntennas#57]
I have noticed that after using KSP burst with real antennas, the game does not load at all. It gets stuck on "loading part upgrades" . As mentioned by principia author here - " Since 1.12 the mods that have DLLs with an empty "File Version" will fail to load and the game will be stuck on "loading part upgrades". "

 So I think u have to do this. I have double checked kspburst is causing it to get stuck. You can refer to the whole discussion [Here](https://forum.kerbalspaceprogram.com/index.php?/topic/203262-stuck-on-loading-part-upgrades-112/)

**Comment by DRVeyl** [comment]
Thanks.  We'll look at KSPBurst [and the Unity dlls it packages, which seems to be the issue].

**Comment by DRVeyl** [comment]
Please try <https://github.com/KSPModdingLibs/KSPBurst/releases/tag/v1.5.4.0> and report if that fixes?

**Comment by DRVeyl** [comment]
Closing with the release of RA v2.1 and KSPBurst v1.5.4.0
