### ISSUE TITLE
Feature Request: Occlude DSN icons on opposite side

### ISSUE THREAD

**Issue by thunder175** [DRVeyl/RealAntennas#58]
Currently ground stations on the opposite side of view are not occluded, but rather lightly subdued. When adding more tracking stations this can lead to a large amount of icons cluttering the view. Please consider adding an option to make the unseen station icons disappear from from when rotating the planet in map view.

**Comment by DRVeyl** [comment]
Unfortunately, RA isn't at all involved in how the icons present themselves.  RA just declares that there -are- icons for KSP to draw.

Are there any -other- icons, like vessels/landers/probes that have the behaviour you're asking for, and RA just isn't setting a correct field?

**Comment by thunder175** [comment]
If just noticed that the Commnet groundstations when using Commnet Constellation for example, or even Remotetech have an option to hide icons when not in direct line of sight with the viewer. Maybe see how they do it? I'm not a coder for KSP so wouldn't even know where to start. Its not a huge deal and I would only classify this a a low priority feature.

**Comment by DRVeyl** [comment]
RemoteTech I think does a lot on its own, but <https://github.com/KSP-TaxiService/CommNetConstellation/blob/develop/src/CommNetConstellation/CommNetLayer/CNCCommNetUI.cs#L129> seems like a reasonable reference.  I hadn't considered playing more with <https://www.kerbalspaceprogram.com/api/class_k_s_p_1_1_u_i_1_1_screens_1_1_mapview_1_1_map_node.html>.  Will look into it!

**Comment by thunder175** [comment]
Excellent thank you! I'm currently writing up a whole new ground station config for JNSQ with not just the DSN's, but basic ground stations and a couple NEN-like stations. So decluttering the map view in the future would be awesome! I would imagine it would do the same for RSS if one were to add all the same.
