### ISSUE TITLE
Antennas on loaded sub-assemblies will have a broken planner

### ISSUE THREAD

**Issue by Tonas1997** [DRVeyl/RealAntennas#62]
Title. I stored a satellite as a sub-assembly and, when I loaded it back in the VAB, the antenna planner stopped working. Regardless of the setup (band, transmit power, tech level, target...), the bitrate remains at zero. Not sure if this actually affects comms or if it's just an UI problem.

Note that, if you replace the antenna on the sub-assembly with a similar "new" part, it will start working again.

**Versions**
KSP - 1.10
RealAntennas - 2.0.0

**Comment by DRVeyl** [comment]
Cannot duplicate in RA v2.1.  (The planner was completely rewritten.  RA v2.1 was released yesterday.)  Test there, please?

**Comment by Tonas1997** [comment]
New version seems to have fixed the issue. Closing it now 😄
