### ISSUE TITLE
Targeting of relay antennas

### ISSUE THREAD

**Issue by Spacemachine42** [DRVeyl/RealAntennas#70]
When trying to communicate through a ka-band geostationary relay satellite, I can't get a connection unless the antennas on both satellites target eachother.

My understanding was that my science gathering satellite would set the relay as its target, the relay satellite in turn targets a DSN ground station, and the data would be transmitted. All the antennas involved are within range of eachother but I don't get a connetction unless the ka-band antenna on the relay is also targeting the science satellite, and uses its omni to connect to the DSN. 

Is this the way it's supposed to work? If so, that would severely limit the use of relay satellites. IMO, the antenna targeting should only be relevant for transmitting and not for recieving, to allow for many satellites using the same relay to send data without having to constantly retarget the relay antenna.

**Comment by DRVeyl** [comment]
What antenna on the relay are you intending to use to hear from the science-gathering satellite?  If its dish is pointed at a ground station, then it isn't pointed at the probe.  Typically, you should use multiple antennas on the relay.

I suspect you don't have nearly enough link for the Ka-band dish to communicate with just a Ka-band omni on the relay.  The planner will tell you how to inspect this, and the wiki has a guide for setting up relays.
