### ISSUE TITLE
Antenna Targeting Center filter enhancements

### ISSUE THREAD

**Issue by lpgagnon** [DRVeyl/RealAntennas#73]
https://github.com/DRVeyl/RealAntennas/blob/master/src/RealAntennasProject/Targeting/TextureTools.cs#L35

Default set of vessel type filter is hardcoded and resets every time the window is opened. Inconvenient if everything I need to retarget happens to be rovers

Options: default to everything visible, make the active list static, load defaults from a file, persist the active list to disk

**Comment by DRVeyl** [comment]
Fixed by <https://github.com/DRVeyl/RealAntennas/commit/213a79a3888f4b65edb6e41c78654ccb6022b6e7>
