### ISSUE TITLE
Where is the old Antenna Planner range information?

### ISSUE THREAD

**Issue by uncle-buzz** [DRVeyl/RealAntennas#75]
Hi !
First, thanks for your work!
I have upgraded my mods from RP-0 1.10.1 to 1.11.3, and your mod has been upgraded from 1.3 to 2.1. Everything seems to work well, apart from one thing: Where are the range and data rate information from "Antenna Planning" section (the one included in the following image) 
![](https://camo.githubusercontent.com/7dc2f848b8812bd34ddb54942f75488580d3aad203bf616bb130d6a8a2356814/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3332393638353730323234373834313739322f3737373538323032323331343831393539342f756e6b6e6f776e2e706e67) 
since after upgrading the data are shown like this image 
![](https://camo.githubusercontent.com/ce58f8993bf9c13193a202ca71a8ebb0e79b0b2983966d92895caeb656061cb1/68747470733a2f2f692e696d6775722e636f6d2f7a39534b514b6f2e706e67) 
where "Antenna Planning" section has been removed.
Is this due to the planner rewrite or this menu is done by another mod?
Are we forced now to open the Antenna Planner Gui?

**Comment by DRVeyl** [comment]
You now need to open the antenna planning GUI.
