### ISSUE TITLE
Module Manager Fatal Error

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [DRVeyl/RealAntennas#78]
Module Manager throws fatal error. This appears in log.

```
[LOG 13:23:23.255] VesselModules: Found VesselModule of type RACommNetVessel with order 999
[EXC 13:23:23.259] NullReferenceException: Object reference not set to an instance of an object
	RealAntennas.RACommNetVessel.OnDestroy () (at <bcc06e73d2f64d0e87ff02a1c80277a3>:0)
	UnityEngine.Object:DestroyImmediate(Object)
	<>c:<CompileModules>b__4_0(Type)
	LoadedAssembly:TypeOperation(Action`1)
	LoadedAssembyList:TypeOperation(Action`1)
	VesselModuleManager:CompileModules()
	<LoadObjects>d__90:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>d__71:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>d__11:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()
```

Removing RealAntenna stops error.

Version 2.1.1
KSP 1.12.3.3173

**Comment by DRVeyl** [comment]
This was fixed with the latest commit <https://github.com/DRVeyl/RealAntennas/commit/5918116e583847003a62089e514b1e138e32095e>, just haven't re-released.  As best I am aware, this error during the Loading scene does not have any consequence.

**Comment by Glitched-Fox-Studios** [comment]
It does say game needs to be shut down. Hitting okay closed game. If it's fixed in next release, thanks.

**Comment by DRVeyl** [comment]
I'm not sure what you're referring to.  Every user of RA will encounter that specific exception.  I do not know what window or message you are encountering that says "the game needs to be shut down."

You wouldn't by any chance be running Lisias' fork of ModuleManager, perhaps with KSPRecall or something similar?
