### ISSUE TITLE
No power loss from data transfer.

### ISSUE THREAD

**Issue by Aebestach** [DRVeyl/RealAntennas#80]
Hi, when I played in the original environment I found that transferring research data did not consume power.
[video](https://drive.google.com/file/d/11e5d9W3ztmc8YFnr43q0wT0EW096Lg_8/view?usp=sharing)

**Comment by Aebestach** [comment]
I tried it in RSS and found the same lack of power consumption. Is this the way the mod is set up?

**Comment by DRVeyl** [comment]
Probably working as intended.  Looking in the PAW, you see Idle power draw of 11.7W and active of 13.9W.  1W is configured as 0.001EC/s.  You're always paying the idle cost, and the displayed active cost is total, not in addition.  It is likely charging you, it's just rounding error compared to other things going on.

It would be more noticable at lower tech levels.  I assume you're in sandbox, so you're at the maximum tech level, and you haven't had to turn the antenna's power up.  The balance for stock is way off.  The balance for RSS+RO is where I have supporting documentation.

**Comment by Aebestach** [comment]
I understand, thank you.

**Comment by Aebestach** [comment]
Hi, I would like to ask, if I want to change this 0.001, do I change it in the source code or do I need to change the cfg file?

**Comment by DRVeyl** [comment]
In cfg.  The TechLevel data starts here: <https://github.com/DRVeyl/RealAntennas/blob/master/GameData/RealAntennas/RealAntennasCommNetParams.cfg#L100>

Of course, strongly recommend you use ModuleManager patching rather than trying to edit the files as shipped.
```
@RealAntennasCommNetParams:FINAL
{
  @TechLevelInfo[TL9]
  {
    @BasePower = 1
  }
}
```

**Comment by Aebestach** [comment]
thanks
